# Generated by Django 3.2.13 on 2022-04-29 13:57

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nome', models.CharField(max_length=255, verbose_name='Edição')),
                ('descricao', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descrição')),
                ('file', models.FileField(upload_to='informativo/')),
                ('data_publicacao', models.DateTimeField(verbose_name='Data da Publicação')),
            ],
            options={
                'verbose_name': 'edição',
                'verbose_name_plural': 'edições',
                'ordering': ('-data_publicacao',),
            },
        ),
    ]
